import Head from "next/head";
import Link from "next/link";
import type { GetServerSideProps, InferGetServerSidePropsType } from "next";
import { useEffect } from "react";
import { getSalesTenderOpportunity } from "../../../../lib/sales-store";
import { salesDateTimeLocalToIso } from "../../../../lib/sales-dates";

interface Props { record: NonNullable<Awaited<ReturnType<typeof getSalesTenderOpportunity>>>; error?: string; }
const fieldClass = "rounded-md border border-gray-300 px-3 py-2 text-sm";
const statuses = ["NEW", "DOCUMENTS_REQUESTED", "DOCUMENTS_RECEIVED", "SUBMITTED", "AWARDED", "NOT_AWARDED"];

export const getServerSideProps: GetServerSideProps<Props> = async ({ params, query }) => {
  const record = await getSalesTenderOpportunity(typeof params?.id === "string" ? params.id : "");
  if (!record) return { notFound: true };
  return { props: { record, error: typeof query.error === "string" ? query.error : undefined } };
};

function localDate(value?: string) { return value ? new Date(value).toISOString().slice(0, 16) : ""; }
function money(value?: number) { return value == null ? "Not recorded" : value.toLocaleString(undefined, { style: "currency", currency: "EUR" }); }

export default function TenderPage({ record, error }: InferGetServerSidePropsType<typeof getServerSideProps>) {
  const { tender, organization, contacts } = record;
  useEffect(() => {
    const forms = Array.from(document.querySelectorAll("main form"));
    const normalize = (event: Event) => {
      const form = event.currentTarget as HTMLFormElement;
      const input = form.elements.namedItem("nextActionDate");
      if (input instanceof HTMLInputElement && input.value) input.value = salesDateTimeLocalToIso(input.value);
    };
    forms.forEach((form) => form.addEventListener("submit", normalize));
    return () => forms.forEach((form) => form.removeEventListener("submit", normalize));
  }, []);
  return <><Head><title>{tender.name} | Tender Readiness</title><meta name="robots" content="noindex,nofollow" /></Head>
    <main className="min-h-screen bg-gray-50 px-4 py-10 text-gray-900"><div className="mx-auto max-w-5xl">
      <Link href={`/internal/sales/organizations/${organization.id}`} className="text-sm font-medium text-forest-700">← {organization.name}</Link>
      {error ? <div className="mt-4 rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div> : null}
      <div className="mt-5 flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wide text-amber-700">Tender Readiness</p><h1 className="mt-1 text-3xl font-bold tracking-tight">{tender.name}</h1><p className="mt-2 text-sm text-gray-600">{organization.name}{tender.contactName ? ` · ${tender.contactName}` : ""}</p></div><span className="rounded-full bg-amber-100 px-3 py-1 text-sm font-semibold text-amber-800">{tender.status}</span></div>
      <section className="mt-6 grid gap-px overflow-hidden rounded-lg border border-gray-200 bg-gray-100 shadow-sm sm:grid-cols-2 lg:grid-cols-4"><div className="bg-white px-5 py-4"><div className="text-xs uppercase tracking-wide text-gray-500">Buyer</div><div className="mt-1 font-semibold">{tender.buyer || "Not recorded"}</div></div><div className="bg-white px-5 py-4"><div className="text-xs uppercase tracking-wide text-gray-500">Reference</div><div className="mt-1 font-semibold">{tender.referenceNumber || "Not recorded"}</div></div><div className="bg-white px-5 py-4"><div className="text-xs uppercase tracking-wide text-gray-500">Deadline</div><div className="mt-1 font-semibold">{tender.submissionDeadline ? new Date(tender.submissionDeadline).toLocaleString() : "Not recorded"}</div></div><div className="bg-white px-5 py-4"><div className="text-xs uppercase tracking-wide text-gray-500">Contract value</div><div className="mt-1 font-semibold">{money(tender.contractValue)}</div></div></section>
      <section className="mt-6 rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Tender details</h2><form method="post" action="/api/internal/sales" className="mt-4 grid gap-3 md:grid-cols-2"><input type="hidden" name="action" value="update_tender" /><input type="hidden" name="organizationId" value={organization.id} /><input type="hidden" name="tenderId" value={tender.id} /><input required name="name" defaultValue={tender.name} placeholder="Tender name" className={fieldClass} /><select name="contactId" defaultValue={tender.contactId || ""} className={fieldClass}><option value="">No contact</option>{contacts.map((contact) => <option key={contact.id} value={contact.id}>{contact.name}</option>)}</select><input name="buyer" defaultValue={tender.buyer} placeholder="Buyer" className={fieldClass} /><input name="referenceNumber" defaultValue={tender.referenceNumber} placeholder="Reference number" className={fieldClass} /><input name="submissionDeadline" type="datetime-local" defaultValue={localDate(tender.submissionDeadline)} className={fieldClass} /><input name="contractValue" type="number" step="0.01" defaultValue={tender.contractValue} placeholder="Contract value" className={fieldClass} /><input name="sector" defaultValue={tender.sector} placeholder="Sector" className={fieldClass} /><select name="status" defaultValue={tender.status} className={fieldClass}>{statuses.map((status) => <option key={status}>{status}</option>)}</select><input name="documentsRequested" type="number" min="0" defaultValue={tender.documentsRequested} placeholder="Documents requested" className={fieldClass} /><input name="documentsReceived" type="number" min="0" defaultValue={tender.documentsReceived} placeholder="Documents received" className={fieldClass} /><textarea name="notes" defaultValue={tender.notes} placeholder="Notes" className={`${fieldClass} md:col-span-2`} /><button className="rounded-md bg-amber-700 px-4 py-2 text-sm font-medium text-white md:col-span-2">Save tender</button></form></section>
      <section className="mt-6 rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-semibold">Documents</h2><span className="text-sm text-gray-500">{tender.documentsReceived}/{tender.documentsRequested} received</span></div><div className="mt-4 space-y-3">{tender.documents.map((document) => <form key={document.id} method="post" action="/api/internal/sales" className="grid gap-2 rounded-md border border-gray-100 p-3 md:grid-cols-[1fr_auto_auto_auto]"><input type="hidden" name="action" value="update_tender_document" /><input type="hidden" name="organizationId" value={organization.id} /><input type="hidden" name="tenderId" value={tender.id} /><input type="hidden" name="documentId" value={document.id} /><input name="name" defaultValue={document.name} className={fieldClass} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="requested" defaultChecked={document.requested} /> Requested</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="received" defaultChecked={document.received} /> Received</label><button className="rounded bg-gray-900 px-3 py-2 text-xs font-medium text-white">Save</button><textarea name="notes" defaultValue={document.notes} placeholder="Document notes" className={`${fieldClass} md:col-span-4`} /></form>)}</div><form method="post" action="/api/internal/sales" className="mt-4 grid gap-2 md:grid-cols-[1fr_auto_auto_auto]"><input type="hidden" name="action" value="add_tender_document" /><input type="hidden" name="organizationId" value={organization.id} /><input type="hidden" name="tenderId" value={tender.id} /><input required name="name" placeholder="Document requested" className={fieldClass} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="requested" defaultChecked /> Requested</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="received" /> Received</label><button className="rounded bg-amber-700 px-3 py-2 text-xs font-medium text-white">Add</button></form></section>
      <section className="mt-6 rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-semibold">Tender email interactions</h2><span className="text-sm text-gray-500">{tender.interactions.length}</span></div><div className="mt-4 space-y-3">{tender.interactions.map((interaction) => <article key={interaction.id} className="rounded-md border border-gray-100 bg-gray-50 p-3"><div className="text-xs text-gray-500">{new Date(interaction.occurredAt).toLocaleString()} · {interaction.direction} · {interaction.channel}</div><div className="mt-1 font-medium">{interaction.subject || "Interaction"}</div><p className="mt-1 whitespace-pre-wrap text-sm text-gray-700">{interaction.summary}</p></article>)}</div><form method="post" action="/api/internal/sales" className="mt-4 grid gap-3"><input type="hidden" name="action" value="add_interaction" /><input type="hidden" name="organizationId" value={organization.id} /><input type="hidden" name="tenderOpportunityId" value={tender.id} /><select name="contactId" className={fieldClass}><option value="">No contact</option>{contacts.map((contact) => <option key={contact.id} value={contact.id}>{contact.name}</option>)}</select><input name="occurredAt" type="datetime-local" required className={fieldClass} /><select name="direction" className={fieldClass}><option>INBOUND</option><option>OUTBOUND</option><option>INTERNAL</option></select><input type="hidden" name="channel" value="EMAIL" /><input type="hidden" name="interactionType" value="MESSAGE" /><input name="subject" placeholder="Subject" className={fieldClass} /><textarea required name="summary" placeholder="What happened? Keep this factual." className={fieldClass} /><button className="rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-white">Log email interaction</button></form></section>
      <section className="mt-6 rounded-lg border border-amber-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Tender workflow</h2><form method="post" action="/api/internal/sales" className="mt-4 grid gap-3 md:grid-cols-2"><input type="hidden" name="action" value="update_tender" /><input type="hidden" name="organizationId" value={organization.id} /><input type="hidden" name="tenderId" value={tender.id} /><input type="hidden" name="name" value={tender.name} /><input type="hidden" name="contactId" value={tender.contactId || ""} /><input type="hidden" name="buyer" value={tender.buyer || ""} /><input type="hidden" name="referenceNumber" value={tender.referenceNumber || ""} /><input type="hidden" name="submissionDeadline" value={tender.submissionDeadline || ""} /><input type="hidden" name="contractValue" value={tender.contractValue ?? ""} /><input type="hidden" name="sector" value={tender.sector || ""} /><input type="hidden" name="notes" value={tender.notes} /><input type="hidden" name="documentsRequested" value={tender.documentsRequested} /><input type="hidden" name="documentsReceived" value={tender.documentsReceived} /><select name="salesStatus" defaultValue={tender.salesStatus} className={fieldClass}><option>NEW</option><option>CONTACTED</option><option>ENGAGED</option><option>NURTURE</option><option>OPPORTUNITY</option><option>CLOSED_WON</option><option>CLOSED_NO</option><option>PARKED</option><option>DO_NOT_CONTACT</option></select><input name="assignedOwner" defaultValue={tender.assignedOwner} placeholder="Assigned owner" className={fieldClass} /><input name="nextAction" defaultValue={tender.nextAction} placeholder="Next action" className={fieldClass} /><input name="nextActionDate" type="datetime-local" defaultValue={tender.nextActionDate ? new Date(tender.nextActionDate).toISOString().slice(0, 16) : ""} className={fieldClass} /><textarea name="buyerRequirements" defaultValue={tender.buyerRequirements} placeholder="Buyer requirements" className={`${fieldClass} md:col-span-2`} /><button className="rounded-md bg-amber-700 px-4 py-2 text-sm font-medium text-white md:col-span-2">Save tender workflow</button></form></section>
    </div></main></>;
}
